apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: {{ .Values.ghost.replicas }}
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: {{ .Values.ghost.image }}
        env:
        # - name: GHOST_ADMIN_PASSWORD
        #   value: {{ .Values.ghost.adminPassword }}
        - name: NODE_ENV
          value: development
        ports:
        - containerPort: {{ .Values.ghost.containerPort }}
          name: http
      restartPolicy: Always
